CREATE ROLE app_user LOGIN PASSWORD :'app_password';
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION app_user;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE playground FROM PUBLIC;
GRANT CONNECT ON DATABASE playground TO app_user;
GRANT USAGE ON SCHEMA app TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO app_user;
